export enum Airport {
  TIRANA_INTERNATIONAL = 'Tirana International Airport',
  PRISTINA_INTERNATIONAL = 'Pristina International Airport',
  ROME_FIUMICINO = 'Rome Fiumicino Airport',
  JFK = 'John F. Kennedy International Airport',
  TORONTO_PEARSON = 'Toronto Pearson International Airport',
  HEATHROW = 'Heathrow Airport',
  CHARLES_DE_GAULLE = 'Charles de Gaulle Airport',
  FRANKFURT = 'Frankfurt Airport',
  MADRID_BARAJAS = 'Adolfo Suárez Madrid-Barajas Airport',
  LISBON_HUMBERTO_DELGADO = 'Lisbon Humberto Delgado Airport',
  ZURICH = 'Zurich Airport',
  SYDNEY_KINGSFORD_SMITH = 'Sydney Kingsford Smith Airport',
  SAO_PAULO_GUARULHOS = 'São Paulo-Guarulhos International Airport',
  BUENOS_AIRES_EZEIZA = 'Ministro Pistarini International Airport',
  TOKYO_HANEDA = 'Tokyo Haneda Airport',
  BEIJING_CAPITAL = 'Beijing Capital International Airport',
  DELHI_INDIRA_GANDHI = 'Indira Gandhi International Airport',
  JOHANNESBURG_OR_TAMBO = 'O.R. Tambo International Airport',
}
